### ISSUE TITLE
Can we ensure all actors are initialized before any are started?

### ISSUE THREAD

**Issue by jcrossley3** [drogue-iot/drogue-device#23]
It would be nice if we could assume our collaborators have been completely initialized before our actor's `on_start` hook is called. See https://github.com/drogue-iot/drogue-device/commit/53843abd0347fd0123147113d9b3002fac93097f

I guess this would extend to all lifecycle events for any actor: can we assume they're _complete_ rather than merely "waiting"?

**Comment by lulf** [comment]
I think this is less of an issue now that there is only a single hook, and that actors are now started in 'mount order'.
