### ISSUE TITLE
wifi/esp8266 doesn't work with defmt

### ISSUE THREAD

**Issue by ctron** [drogue-iot/drogue-device#44]
It looks like two issues are present:

1. The wifi+esp feature includes `log` (which is not allowed and fails with a compiler error)
2. Some types cannot be passed into `defmt` macros:
    ~~~
    error[E0277]: the trait bound `DriverError: Format` is not satisfied
       --> /home/jreimann/git/drogue-device/device/src/fmt.rs:164:13
        |
    164 |             ::defmt::error!($s $(, $x)*);
        |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Format` is not implemented for `DriverError`
    ~~~

**Comment by lulf** [comment]
@ctron I've added defmt support to all types that had Debug (I think). Let me know if it's improved.
